spring:
  application:
    name: IotDmApplication
  profiles:
    active: dev
  cache:
    redis:
      key-prefix: "IOTdm:"
    type: redis

IOTdm:
  label: IotDmApplication
  version: 1.0.0


## mybatis-plus
mybatis-plus:
  global-config:
    banner: false
    db-config:
      id-type: assign_uuid
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  typeEnumsPackage: com.aibaixun.iotdm.enums



