## spring 配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATASOURCE_HOST:172.16.9.1}:${DATASOURCE_PORT:3306}/iotdm
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:bxzh123456!}
    hikari:
      maximumPoolSize: "${SPRING_DATASOURCE_MAXIMUM_POOL_SIZE:16}"
      connection-timeout: 60000
      idle-timeout: 600000
      minimum-idle: 1

  redis:
    timeout: 6000
    lettuce:
      pool:
        max-active: 1000
        max-wait: -1
        max-idle: 200
        min-idle: 100
      shutdown-timeout: 100
    cluster:
      nodes:
        - 172.16.9.2:6379
        - 172.16.9.3:6379
        - 172.16.9.4:6379
      max-redirects: 3
    database: 0
    sub:
      cluster: redis://172.16.9.2:6379

bx:
  swagger:
    applicationName: IOTdmApplication
    basePackage: com.aibaixun.iotdm.controller
    title: IOTdm Web Api
    path: /**
    enable: true

transport:
  default-keepalive: "${DEFAULT_KEEPALIVE:90}"
  mqtt:
    # mqtt 开关
    enabled: "${MQTT_ENABLED:true}"
    # mqtt 绑定地址
    bind_address: "${MQTT_BIND_ADDRESS:0.0.0.0}"
    # mqtt 绑定端口
    bind_port: "${MQTT_BIND_PORT:1883}"
    netty:
      # netty 监控级别
      leak_detector_level: "${NETTY_LEAK_DETECTOR_LVL:DISABLED}"
      # boss 线程数
      boss_group_thread_count: "${NETTY_BOSS_GROUP_THREADS:1}"
      # work 线程数
      worker_group_thread_count: "${NETTY_WORKER_GROUP_THREADS:12}"
      # 负载内容
      max_payload_size: "${NETTY_MAX_PAYLOAD_SIZE:65536}"
      # 开启keep alive
      so_keep_alive: "${NETTY_SO_KEEPALIVE:false}"
    ssl:
      enabled: "${MQTT_SSL_ENABLED:false}"
      bind_address: "${MQTT_SSL_BIND_ADDRESS:0.0.0.0}"
      bind_port: "${MQTT_SSL_BIND_PORT:1883}"
      protocol: "${MQTT_SSL_PROTOCOL:TLSv1.2}"

  limit:
    # ip 限制开关
    ip_limit_enabled: "${TRANSPORT_IP_LIMITS_ENABLED:false}"
    # 限制 过期时间
    ip_block_timeout: "${TRANSPORT_IP_BLOCK_TIMEOUT:60000}"
    # 错误次数
    max_wrong_credentials_per_ip: "${TRANSPORT_MAX_WRONG_CREDENTIALS_PER_IP:10}"
    # 租户限制 速率限制
    tenant_rate_limit: "${TENANT_RATE_LIMIT:}"
    # 租户限制
    tenant_num_limit: "${TENANT_RATE_LIMIT:90}"